### ISSUE TITLE
on debian, /var/lib/dpkg/info/stellar-horizon.postinst: line 36: sudo: command not found

### ISSUE THREAD

**Issue by ilrico** [stellar/packages#17]
blocks db migration on non-sudo debian systems

**Comment by brahman81** [comment]
Hi Ilrico,

As of now, the packages are only tested on Ubuntu.

Unlike Debian, Ubuntu doesn't set a root password, which is why `sudo` is installed by default and why we make use of it to simplify the `postinst` scripts.

Please feel free to submit a PR replacing the use of `sudo` with another method for gaining root privileges (`runuser` ? )
