### ISSUE TITLE
overrides don't seem right

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/packages#37]
@brahman81 

I think you got things backwards in #36 (not an expert in this - working off `man dpkg-buildflag`) 
* the package should use `DEB_flag_PREPEND` to set defaults for `CFLAGS`, `CXXFLAGS`, `LDFLAGS`
* when building, caller should set `DEB_flag_APPEND` to override whatever default was set (with the way things are, overrides don't really work it seems)

Also
* it looks like there is no good default for `CFLAGS` now (that also needs to be set otherwise it defaults to some other thing inside configure scripts)
* I would add something in the readme.debian so that people know about this

**Comment by brahman81** [comment]
@MonsieurNicolas,

Until now we have only been overriding `CXXFLAGS` in the `debian/rules` file for the stellar-core package and relying on the Ubuntu defaults provided by `dpkg-buildflags` for `CFLAGS` and `LDFLAGS`:

```
# dpkg-buildflags | egrep '^(C|CPP|CXX|LD)FLAGS'
CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security
CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security
LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro
``` 
#36 introduces partial overriding of the `CXXFLAGS` buildflag as returned by `dpkg-buildflags`.

We effectively append some flags to `CXXFLAGS` to enforce use of `libc++` and `libcxxabi`. This is achieved by using `DEB_CXXFLAGS_MAINT_APPEND` variable, but we could prepend too if you prefer.

At build time, the  `dpkg-buildflags` system allows us to specify extra custom `CXXFLAGS` in our build environments by using `DEB_CXXFLAGS_SET`. Because we use `DEB_CXXFLAGS_MAINT_APPEND` in our `debian/rules` we can still ensure we build with the correct standard C++ library, as denoted in the build dependency list.

#36 also enables us to set `CFLAGS` by using `DEB_CFLAGS_SET` at build time which overrides `dpkg-buildflags` defaults, because we do not use `DEB_CFLAGS_MAINT_APPEND/PREPEND` in `debian/rules` it is effectively a complete override.

If we do not need to deviate from the Ubuntu default `CFLAGS`, then it would be better not to set any in the `debian/rules` make file either. This way overriding `CFLAGS` is achieved by setting `DEB_CFLAGS_SET` in our build environment.

#36 also introduces the "parameterisation" of the configure options, this can be achieved by setting the `DEB_CONFIGURE_OPTS` environment variable during build time or if not set it falls back to the defaults specified in `debian/rules`.

I have updated the packages README.md, explaining how to override the compile flags:

https://github.com/stellar/packages#building-packages

**Comment by MonsieurNicolas** [comment]
Yes, we need to prepend defaults instead. Right now we end up with situations where we cannot actually override whatever is going on inside the package guts, for example I end up with things like this
```-g1 -O2 -fstack-protector-strong -Wformat -Werror=format-security -stdlib=libc++ -fno-omit-frame-pointer -O3 -ggdb```

as compilers parse parameters from left to right, the `-O3 -ggdb` takes precedence over my custom settings `-O2 -g1`.
