### ISSUE TITLE
Horizon deb package failed to install due to existing DB

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/packages#42]
A user installing `stellar-horizon` on Ubuntu ran into the failure scenario described in [this SE question](https://stellar.stackexchange.com/questions/2398/how-to-configure-package-stellar-horizon-postgres).

The Horizon migrations table already existed (but with no rows?!) and this caused the installation to fail.

```
Setting up stellar-horizon-postgres (0.1-5) ...
2019/04/05 11:30:38 exec failed: pq: relation "gorp_migrations" already exists
dpkg: error processing package stellar-horizon-postgres (--configure):
 subprocess installed post-installation script returned error exit status 1
```

It seems the DB may not be removed properly on the previous uninstall. Or, if we intend to support this scenario, we need to handle the existing state better, either by asking for confirmation for update or failing with a more useful error message.

**Comment by amissine** [comment]
The first time I got the `Package stellar-horizon-postgres is not configured yet.` error message was when I was running `sudo apt-get update && sudo apt-get install stellar-quickstart` for the first time. The `horizon` db has been created with one empty table `gorp_migrations` in it. Then the error message was shown.

**Comment by amissine** [comment]
On another Ubuntu box, `sudo apt-get update && sudo apt-get install stellar-quickstart` ran successfully, but service `stellar-core` failed to start. After I started it manually, synced, and started `stellar-horizon`, everything was fine. More info, if needed, is [here](https://docs.google.com/document/d/15Yz3Xg03VQ2C1OT47MYARBiQbuAG-ttePVtgCFgBwGw/edit).

**Comment by brahman81** [comment]
@amissine @ire-and-curses Thank you both for reporting this issue!

The `stellar-horizon` package does not create a `horizon` database, creating the `horizon` db is handled by the `stellar-horizon-postgres` package. This is by design.

The edge case you encountered exists because although the `stellar-horizon` package doesn't create the `horizon` db it does run the Horizon migrations as part of it's `stellar-horizon.postinst configure` maintainer script step. We do this to ensure seamless schema migrations during installs/upgrades of Horizon.

I believe that in this instance, you must have created a `horizon` database but not run `stellar-horizon-cmd db init` to create the db schema. When you installed the `stellar-horizon` package it would have attempted to run the migrations on an empty `horizon` db (creating the `gorp_migrations` table only).

When you subsequently installed the `stellar-quickstart` package the database already existed but not the schema which caused the installation of stellar-horizon-postgres to fail, cascading all the way back to the `stellar-quickstart` installation failure.

Going forwards, I have modified the `stellar-horizon` postinst script to check if the schema has been created prior to running `db migrate up` (#43),  this should prevent this from occurring again.

**Comment by ire-and-curses** [comment]
Awesome, thanks @brahman81!
